services:
  db:
    image: postgres:latest
    container_name: storage_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: competitoreventresult
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  storage-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage_service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/competitoreventresult
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  pg_data:
